export const projects = [
	{
		title: 'React Flip Clock Time Tracker',
		date: 'Apr 2022',
		source: 'https://github.com/aaron-soto/react-clock',
		demo: 'https://aaron-soto.github.io/react-clock/',
		description: 'A flip style clock to display and keep track of time.',
		image: 'react-clock.png',
	},
	{
		title: 'Ninja Gold Canvas Game',
		date: 'Feb 2022',
		source: 'https://github.com/aaron-soto/NinjaGoldGame',
		demo: 'https://aaron-soto.github.io/NinjaGoldGame/',
		description: 'A Canvas game where player can "earn" and "gamble" coins.',
		image: 'ninjagoldgame.png',
	},
	{
		title: 'React Hangman',
		date: 'Apr 2022',
		source: 'https://github.com/aaron-soto/react-hangman',
		demo: 'https://aaron-soto.github.io/react-hangman/',
		description: 'A react version of the classic Hangman Game',
		image: 'react-hangman.png',
	},
	{
		title: 'React Search Bar',
		date: 'Oct 2021',
		source: 'https://github.com/aaron-soto/react-search',
		demo: 'https://aaron-soto.github.io/react-search/',
		description: 'A React search bar with real time filters.',
		image: 'react-search.png',
	},
	{
		title: 'React ToDo App',
		date: 'Feb 2022',
		source: 'https://github.com/aaron-soto/to-do-app',
		demo: 'https://aaron-soto.github.io/to-do-app/',
		description: 'A Clean looking ToSo app to help stay productive.',
		image: 'react-todo.png',
	},
	{
		title: 'Nintendo Site Clone',
		date: 'Jan 2022',
		source: 'https://github.com/aaron-soto/nintendo-react',
		demo: 'https://aaron-soto.github.io/nintendo-react/',
		description:
			'A React clone of a page from the nintendo page with interactions.',
		image: 'nintendo-clone.jpg',
	},
];
